#!/bin/bash

alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias less="less -r"
alias ls="ls --color=auto -F"
alias ll="ls -l"
alias la="ls -A"
alias pushd="pushd >/dev/null"
alias popd="popd >/dev/null"
alias pssh="pssh -t 0"

# Mock
alias f21mock64="mock -r fedora-21-x86_64"
alias f21mock32="mock -r fedora-21-i386"
alias f22mock64="mock -r fedora-22-x86_64"
alias f22mock32="mock -r fedora-22-i386"
alias f23mock64="mock -r fedora-23-x86_64"
alias f23mock32="mock -r fedora-23-i386"
alias rhel6mock64="mock -r epel-6-x86_64"
alias rhel6mock32="mock -r epel-6-i386"
alias rhel7mock64="mock -r epel-7-x86_64"

